//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunningEvent
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int ActivityId { get; set; }
        public System.DateTime Date { get; set; }
        public string Duration { get; set; }
        public Nullable<double> Distance { get; set; }
        public int UnitId { get; set; }
        public string Race { get; set; }
        public string Notes { get; set; }
    
        public virtual RunningActivity RunningActivity { get; set; }
        public virtual RunningPerson RunningPerson { get; set; }
        public virtual RunningUnit RunningUnit { get; set; }
    }
}
